### ISSUE TITLE
Port availability check does not always work

### ISSUE THREAD

**Issue by aldaris** [mryan43/arquillian-available-port-extension#1]
Steps to reproduce:
- start up a WildFly that by default runs on 127.0.0.1:8080
- try to use AvailablePortFinder to find a free port

AvailablePortFinder tries to bind against 0.0.0.0 interface, which works apparently in this scenario, but the port isn't actually available. This can cause test failures if the chosen connector (in my case WildFly) tries to bind to 127.0.0.1 instead of 0.0.0.0.

**Comment by mryan43** [comment]
0.0.0.0 is not really a network interface. it has a different meaning depending on where it is used.  It can mean "default gateway" for routing, "not yet initialized" for DHCP, or "All network adresses" in the case of socket binding.

So if a port is already bound on 127.0.0.1, the AvailablePortFinder should not be able to bind the same port on 0.0.0.0 
To try to reproduce your problem, I have explicitly bound 2 sockets to the loopback address in the test class  like this : 
        ServerSocket alreadyUsedSocket = new ServerSocket(8080, 50, InetAddress.getByName("127.0.0.1"));
        ServerSocket alreadyUsedSocket2 = new ServerSocket(8081, 50, InetAddress.getByName("127.0.0.1"));

and the test properly found port 8082 as available :-/

What OS and JVM are you using ?

**Comment by mryan43** [comment]
I downloaded wildfly 10.0.0.CR2 and started a standalone instance on my machine. I was unfortunately not able to reproduce your issue... my tests successfully ran with a container bound to another port (8081).

I'm on Ubuntu  14.04 with Oracle JVM 1.8_025.

**Comment by aldaris** [comment]
I think the main difference is probably that I've tried this on a Mac, I'll try to write a unit test for this..

**Comment by mryan43** [comment]
I also tested this on windows, this bug seems to affect only Mac OS... I'll see if I can still make it work on Mac OS by listing all network interfaces and binding on all of them separately.

**Comment by mryan43** [comment]
I don't have a mac to reproduce your issue right now, however I have modified the code to list all network interfaces and explicitly bind port candidates on each of them to try to fix the compatibility issue.

I have released this in 1.0.2, can you try again ?

**Comment by aldaris** [comment]
Really sorry about the late response: just tested the 1.0.2 version, and it does appear to work correctly now. I can see with the debugger, that it first tries to bind with IPv6 then IPv4 - both succeeding -, then it attempts with 127.0.0.1 and that fails, causing the extension to advance to the next port number.

**Comment by mryan43** [comment]
Glad it helped !
